### ISSUE TITLE
NameError: name 'temperature' is not defined

### ISSUE THREAD

**Issue by mickekring** [mickekring/Self-Watering-Empire-Pot#2]
Traceback (most recent call last):
  File "empirepot.py", line 637, in <module>
    Main()
  File "empirepot.py", line 605, in Main
    water_reading()
  File "empirepot.py", line 134, in water_reading
    logging()
  File "empirepot.py", line 304, in logging
    print("\n{0},{1},{2},{3}".format(strftime("%Y-%m-%d %H:%M:%S"),str(temperature),str(humidity),str(waterLevel)))
NameError: name 'temperature' is not defined

**Comment by mickekring** [comment]
Added
`humidity, temperature = Adafruit_DHT.read_retry(11, 4)`
to function "logging".
